# Generated by Django 4.0.2 on 2023-11-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwrd',
            field=models.CharField(default=100, max_length=255),
            preserve_default=False,
        ),
    ]
