# Generated by Django 4.0.2 on 2023-11-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_passwrd'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=100, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
